### ISSUE TITLE
Broken link in Simple Feature WFS (ESRI) section

### ISSUE THREAD

**Issue by nmtoken** [OneGeology/documentation#9]
https://onegeology.github.io/documentation/providingdata.html#id84

> For more information on how to create a simple feature WFS service and how to edit its GetCapabilities document, go to the WMS section of this cookbook or to ESRI’s documentation about WFS services.

The WFS services link in the above text is broken. currently going to:

http://server.arcgis.com/en/server/latest/publish-services/windows/wfs-services.htm

**Comment by bgsmase** [comment]
The link seems to work to me. Is there something wrong with where it goes or was it maybe just temporarily down?

**Comment by nmtoken** [comment]
working for me too, must have been a temporary glitch
